# Generated by Django 6.0 on 2026-01-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_assignment_created_by_alter_assignment_task"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="unique_task_assignment",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="user",
        ),
        migrations.DeleteModel(
            name="StatusHistory",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
