# Generated by Django 6.0 on 2025-12-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='actor',
        ),
    ]
